# 数据集配置

# 数据根目录
data_root: "data"

# 数据集信息
datasets:
  # 训练集
  train:
    name: "colony_train"
    version: "1.0.0"
    description: "菌落检测训练数据集"
    accession_number: "DCP-TRAIN-001"
    download_url: "https://example.com/datasets/colony_train_v1.0.0.zip"
    format: "zip"
    size: 1024000000  # 1GB
    checksum: "a1b2c3d4e5f6g7h8i9j0"  # SHA-256
    license: "CC BY-NC-SA 4.0"
    citation:
      title: "A Comprehensive Dataset for Colony Detection and Analysis"
      authors: ["Smith, J.", "Johnson, K.", "Williams, L."]
      year: 2023
      journal: "Scientific Data"
      doi: "10.1038/s41597-023-00000-0"
      url: "https://doi.org/10.1038/s41597-023-00000-0"
    splits:
      train: "train"
      validation: "val"
      test: "test"
    metadata:
      image_count: 10000
      resolution: "2048x2048"
      format: "PNG"
      classes: ["background", "colony"]
      
  # 验证集
  validation:
    name: "colony_validation"
    version: "1.0.0"
    description: "菌落检测验证数据集"
    accession_number: "DCP-VAL-001"
    download_url: "https://example.com/datasets/colony_validation_v1.0.0.zip"
    format: "zip"
    size: 102400000  # 100MB
    checksum: "b2c3d4e5f6g7h8i9j0k1"  # SHA-256
    license: "CC BY-NC-SA 4.0"
    citation:
      title: "A Comprehensive Dataset for Colony Detection and Analysis"
      authors: ["Smith, J.", "Johnson, K.", "Williams, L."]
      year: 2023
      journal: "Scientific Data"
      doi: "10.1038/s41597-023-00000-0"
      url: "https://doi.org/10.1038/s41597-023-00000-0"
    splits:
      validation: "val"
    metadata:
      image_count: 1000
      resolution: "2048x2048"
      format: "PNG"
      classes: ["background", "colony"]
      
  # 测试集
  test:
    name: "colony_test"
    version: "1.0.0"
    description: "菌落检测测试数据集"
    accession_number: "DCP-TEST-001"
    download_url: "https://example.com/datasets/colony_test_v1.0.0.zip"
    format: "zip"
    size: 102400000  # 100MB
    checksum: "c3d4e5f6g7h8i9j0k1l2"  # SHA-256
    license: "CC BY-NC-SA 4.0"
    citation:
      title: "A Comprehensive Dataset for Colony Detection and Analysis"
      authors: ["Smith, J.", "Johnson, K.", "Williams, L."]
      year: 2023
      journal: "Scientific Data"
      doi: "10.1038/s41597-023-00000-0"
      url: "https://doi.org/10.1038/s41597-023-00000-0"
    splits:
      test: "test"
    metadata:
      image_count: 1000
      resolution: "2048x2048"
      format: "PNG"
      classes: ["background", "colony"] 