# 训练配置
training:
  epochs: 100
  save_interval: 5
  early_stopping: 10
  mixed_precision: true
  gradient_clipping: 1.0
  accumulation_steps: 1
  validation_interval: 1
  seed: 42

# 模型配置
model:
  name: "unet"
  in_channels: 3
  out_channels: 1
  features: [64, 128, 256, 512]
  dropout: 0.1
  normalization: "batch"
  activation: "relu"

# 数据配置
data:
  batch_size: 16
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  train_transforms:
    - name: "RandomHorizontalFlip"
      p: 0.5
    - name: "RandomVerticalFlip"
      p: 0.5
    - name: "RandomRotation"
      degrees: 30
    - name: "ColorJitter"
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
  val_transforms:
    - name: "Resize"
      size: [512, 512]
    - name: "Normalize"
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# 优化器配置
optimization:
  optimizer: "adamw"
  learning_rate: 0.001
  weight_decay: 0.0001
  momentum: 0.9
  scheduler:
    name: "cosine"
    warmup_epochs: 5
    min_lr: 0.00001
    
# 分布式训练配置
distributed:
  enabled: false
  backend: "nccl"
  world_size: 1
  rank: 0
  
# 日志配置
logging:
  level: "INFO"
  save_interval: 100
  metrics:
    - "loss"
    - "dice"
    - "iou"
  use_wandb: true
  project_name: "segmentation"
  
# 资源监控配置
monitoring:
  enabled: true
  interval: 60  # 秒
  save_plots: true
  alert_threshold:
    cpu_percent: 90
    memory_percent: 90
    gpu_load: 90
    gpu_memory: 90 